Adds support for HKCorrelation
StanfordBDHG/HealthKitOnFHIR pull request #17
Opened 2022-12-04 01:15 UTC by vishnuravi

# Adds support for HKCorrelation

## :recycle: Current situation & Problem
- HealthKit uses correlations to represent blood pressure, by grouping the systolic and diastolic blood pressure samples together. These values should also be grouped as components in a FHIR observation.

## :bulb: Proposed solution
- This PR adds support for converting an HKCorrelation into a FHIR observation with its quantity samples represented as separate components in the observation.
- HealthKit also includes food correlations, which are not addressed here.

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md):
- [X] I agree to follow the [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md).

2022-12-04 01:32 UTC, PSchmiedmayer requested changes
Thank you @vishnuravi for taking a look at HKCorrelationTypes! 

I have added some comments about code reusability and making the configuration more flexible. Let me know if you have any questions there 👍

2022-12-04 01:32 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HealthKit Extensions/HKCorrelationType+Observation.swift
> +            observation.appendComponent(component)
I would suggest to move this logic to the  `HKQuantitySample` extensions (e.g., a `buildQuantitySampleObservationComponent` function)and see if we an identify some code reuse between the creation of an observation and an observationComponent in e.g. a shared private function to create the `Quantity` we we don't have to change to logic at two places if we would modify the mapping logic.

2022-12-04 01:32 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HealthKit Extensions/HKCorrelationType+Observation.swift
> +        observation.appendCategory(CodeableConcept(coding: [vitalSignsCoding]))
I am brainstorming there: Would it make sense to create a similar JSON-bases structure like we have it for the `HKQuantitySampleMapping`s (maybe even reusing some types there) for `HKCorrelation`s so we don't have to hardcode the values there?
Might be wise to test this functionality with multiple `HKCorrelation` types so we know that the mechanism works similar to the functionality for `HKQuantitySample`s 👍

2022-12-04 01:32 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HKQuantitySampleMapping.swift
> +public struct HKQuantitySampleMapping: Codable {
Thank you for fixing the typo @vishnuravi! 🚀

2022-12-04 01:37 UTC, vishnuravi commented on Sources/HealthKitOnFHIR/HealthKit Extensions/HKCorrelationType+Observation.swift
> +        observation.appendCategory(CodeableConcept(coding: [vitalSignsCoding]))
HealthKit only groups two types of data into `HKCorrelation` at the moment - blood pressure and food (nutritional contents). Do you think there would be a need for a separate JSON structure?

2022-12-04 01:53 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HealthKit Extensions/HKCorrelationType+Observation.swift
> +        observation.appendCategory(CodeableConcept(coding: [vitalSignsCoding]))
Yes, I think the consistency would make sense and it would also allow developers to configure the mapping similar to the mappings we have for HKSamples using the Swift structs or a JSON as they conform to Codable 👍

2022-12-04 01:54 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HealthKit Extensions/HKCorrelationType+Observation.swift
> +        observation.appendCategory(CodeableConcept(coding: [vitalSignsCoding]))
We could also think about combining the two into a single JSON with a top level key to differentiate between the use cases. Might make the API a bit cleaner as well compared to passing in multiple configuration types.

2022-12-04 01:55 UTC, vishnuravi commented on Sources/HealthKitOnFHIR/HealthKit Extensions/HKCorrelationType+Observation.swift
> +        observation.appendCategory(CodeableConcept(coding: [vitalSignsCoding]))
I agree, combining everything into a single JSON file makes the most sense.

2022-12-04 02:05 UTC, vishnuravi commented on Sources/HealthKitOnFHIR/HealthKit Extensions/HKCorrelationType+Observation.swift
> +            observation.appendComponent(component)
Thank you @PSchmiedmayer for the suggestion, I have implemented this in [428bbf5].(https://github.com/StanfordBDHG/HealthKitOnFHIR/pull/17/commits/428bbf53845670f899750228280b7bc930fcf5c8)

2022-12-04 20:20 UTC, vishnuravi commented on Sources/HealthKitOnFHIR/HealthKit Extensions/HKCorrelationType+Observation.swift
> +        observation.appendCategory(CodeableConcept(coding: [vitalSignsCoding]))
This has been completed in [12b04ac](https://github.com/StanfordBDHG/HealthKitOnFHIR/pull/17/commits/12b04acb9479afc0aee160e47bb017e4b1c5700e)

2022-12-05 00:19 UTC, PSchmiedmayer reviewed
Thank you for the improvements @vishnuravi! I have one additional round of comments, after that I am hopeful that the PR is ready to be merged, thanks for all the work that went into the improvements! 🚀

2022-12-05 00:19 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HKSampleMapping.swift
> +            }
Looking at this code I noticed that we just check the validity for the default options we provide but not for any user-provided e.g., JSON serialization or object created using the Swift initializers. Therefore I would suggest that we move the checks into an initializer of the `HKSampleMapping` struct. 

This might also require writing a custom `Decodable` initializer that decodes the two properties from a keyed container (we can still use the autogenerated coding keys) and then calls the main initializer to check the validity of the keys. Otherwise these checks would not be performed if e.g. someone just initializes the types from a JSON file or a normal initializer.

2022-12-05 00:19 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HKSampleMapping.swift
> +    public let categories: [MappedCode]
The type should have a public initializer, otherwise one can not initializer a mapping from outside the module. It would be good if the initializer could include the checks that we currently just have in the default value.

2022-12-05 00:19 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HKSampleMapping.swift
> +            }
The same commend that I had above also applies here. I did not think about this when implementing the feature in the last PR but looking at the code made it clear to me that we are checking in the wrong place.

2022-12-05 00:19 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HKSampleMapping.swift
> +            _ = HKUnit(from: mapping.value.unit.hkunit)
The unit check should move into the `MappedUnit` initializer and would therefore probably also result in the creation of a custom `Decodable` initializer there.

2022-12-05 00:19 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HKSampleMapping.swift
> +
My coding conventions so far have been adding two lines between types and "groups" in types, e.g. between initializers (separated by a single line) and the following functions (that are then also separated by a single line).

2022-12-05 00:19 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HKSampleMapping.swift
> +public struct HKCorrelationMapping: Codable {
It might make sense to move the types into separate files and create a `HKSampleMapping` subfolder.

2022-12-05 00:19 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HealthKit Extensions/HKCorrelationType+Observation.swift
> +                continue
Would it make sense to throw an "unsupported" error here just to ensure that we don't accidentally loose any information in the transformation without the user being aware? Even if it might be guaranteed that every object is an `HKQuantitySample` it would be a good way to future-proof the library if that changes within HealthKit.

2022-12-05 00:19 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HealthKit Extensions/HKQuantitySample+Observation.swift
>      }
Nice, I like the reuse here 🚀

2022-12-05 00:19 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/Resources/HKSampleMapping.json
> +    "correlationMapping": {
Might be nice to make these custom CodingKeys and name the top level types `HKCorrelation` and `HKQuantitySample` in consistency with the other keys that we use what also follow the HealthKit (HK) naming. But you can overrule that idea if you don't feel the same here 👍

2022-12-05 00:19 UTC, PSchmiedmayer commented on Tests/HealthKitOnFHIRTests/ObservationExtensionsTests.swift
> +        )
If you move the lines before the `XCTAssertEqual` checks above to ensure that you test the insertion of the components when the collection is nil, then perform some `XCTAssertEqual` checks on the components, and then add additional components with additional checks that then append to a non-nil collection. This might also be the case why the test coverage dropped in the
```
self[keyPath: collection] = []
self[keyPath: collection]?.reserveCapacity(elements.count)
```
lines in the Sources/HealthKitOnFHIR/Observation Extensions/Observation+Collections.swift file.

2022-12-05 17:52 UTC, PSchmiedmayer approved these changes

2022-12-05 18:13 UTC, merged