Convert HKCategorySamples to FHIR Observations
StanfordBDHG/HealthKitOnFHIR pull request #25
Opened 2022-12-19 01:30 UTC by vishnuravi

# Add support for HKCategoryType samples

## :recycle: Current situation & Problem
The current package does not convert HKCategorySamples to FHIR Observations.

## :bulb: Proposed solution
Adds support for all HKCategoryTypes

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md):
- [X] I agree to follow the [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md).

2022-12-19 07:58 UTC, PSchmiedmayer requested changes
@vishnuravi Thanks for the great improvements! The additions look good and are a huge next step to supporting almost all HealthKit types! 🚀

I have added some comments throughout the PR to improve the code structure and documentation. Let me know if you have any questions or feedback to my comments! 👍

2022-12-19 07:58 UTC, PSchmiedmayer commented on Documentation/SUPPORT_TABLE.md
> +- [HKQuantityType](QUANTITY_TABLE.md)
Would be cool if we could display the statistics (Supports X of Y HKCategoryType here). I think this is a nice stat to share.

2022-12-19 07:58 UTC, PSchmiedmayer commented on Documentation/CATEGORY_TABLE.md
> +HealthKitOnFHIR supports 26 category types.
Would be cool if we can compare this to the overall number of `HKCategoryType` available in HealthKit.

2022-12-19 07:58 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HealthKit Extensions/HKCategorySample+Observation.swift
> +        var valueString: String?
The value is never mutated and can therefore be made a constant:
```suggestion
        let valueString: String?
```

2022-12-19 07:58 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HealthKit Extensions/HKCategorySample+Observation.swift
> +        guard let valueString else { throw HealthKitOnFHIRError.notSupported }
I would suggest to use line breaks for guard statements to more easily see the throwing expression.
```suggestion
        guard let valueString else {
            throw HealthKitOnFHIRError.notSupported
        }
```

2022-12-19 07:58 UTC, PSchmiedmayer commented on Tests/HealthKitOnFHIRTests/HKCategorySampleTests.swift
> +            type: HKCategoryType(.audioExposureEvent),
To remove the warning:
```suggestion
            type: HKCategoryType(.environmentalAudioExposureEvent),
```

2022-12-19 07:58 UTC, PSchmiedmayer commented on Tests/HealthKitOnFHIRTests/HKCategorySampleTests.swift
> +                categoryType: HKCategoryType(.audioExposureEvent).description,
To remove the warning:
```suggestion
                categoryType: HKCategoryType(.environmentalAudioExposureEvent).description,
```

2022-12-19 07:58 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HealthKit Extensions/HKCategorySample+Observation.swift
> +        let categoryTypeString = self.categoryType.description
You can move this statement in the switch statement case where it is used.

2022-12-19 07:58 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HealthKit Extensions/SupportedCodeSystem.swift
> +enum SupportedCodeSystem: String {
Might be useful to directly use `FHIRURI` or `URL` as the raw value.

2022-12-19 07:58 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HealthKit Extensions/SupportedCodeSystem.swift
> +enum SupportedCodeSystem: String {
As this type is only used in the unit tests I would suggest moving it over there. Or it would be good to use it in the main target instead of string literals or as e.g. an argument to the Swift interface. 

If we make it an argument to the Swift interface I would suggest to make this an `struct` so it can be more easily extended from the outside and use static constants as the default values. It would look the same from an API surface level (without the functionality to use it in switch statements without a default value) and one can easily extend it in an other page and still use the API surface:
```swift
public struct SupportedCodeSystem {
    let system: URL
    
    
    public static let loinc = SupportedCodeSystem(system: URL(string: "http://loinc.org")!)

    
    public init(system: URL) {
        self.system = system
    }
}
```

2022-12-19 09:04 UTC, vishnuravi commented on Tests/HealthKitOnFHIRTests/HKCategorySampleTests.swift
> +            type: HKCategoryType(.audioExposureEvent),
I have tried this, but the corresponding string value of this type "HKCategoryTypeIdentifierEnvironmentalAudioExposureEvent" is failing validation when being read in from the JSON mapping.

`HealthKitOnFHIR/HKSampleMapping.swift:58: Fatal error: HKCategoryType for the String value HKCategoryTypeIdentifierEnvironmentalAudioExposureEvent does not exist.`

2022-12-19 09:10 UTC, vishnuravi commented on Tests/HealthKitOnFHIRTests/HKCategorySampleTests.swift
> +                categoryType: HKCategoryType(.audioExposureEvent).description,
See comment above.

2022-12-19 09:46 UTC, vishnuravi commented on Sources/HealthKitOnFHIR/HealthKit Extensions/SupportedCodeSystem.swift
> +enum SupportedCodeSystem: String {
Thanks! I don't see this being used outside of the unit tests at the moment, so I will move it there but will keep this alternative suggestion in mind if it needs to be used in the main target later on.

2022-12-19 09:47 UTC, vishnuravi commented on Sources/HealthKitOnFHIR/HealthKit Extensions/SupportedCodeSystem.swift
> +enum SupportedCodeSystem: String {
I am not sure this is possible, as the raw value needs to be a literal?

2022-12-19 09:49 UTC, vishnuravi commented on Sources/HealthKitOnFHIR/HealthKit Extensions/SupportedCodeSystem.swift
> +enum SupportedCodeSystem: String {
How would you do this, as the raw value needs to be a literal?

2022-12-19 17:46 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HealthKit Extensions/SupportedCodeSystem.swift
> +enum SupportedCodeSystem: String {
Sounds good! 👍

2022-12-19 17:47 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HealthKit Extensions/SupportedCodeSystem.swift
> +enum SupportedCodeSystem: String {
You are right, an enum-based approach would not work for that. The best way would most probably be the usage the struct-based route that I have outline in the other comment: https://github.com/StanfordBDHG/HealthKitOnFHIR/pull/25#discussion_r1051901669

2022-12-19 17:48 UTC, PSchmiedmayer commented on Tests/HealthKitOnFHIRTests/HKCategorySampleTests.swift
> +            type: HKCategoryType(.audioExposureEvent),
Thank you, I will take a look at the branch, thanks for reproducing the issue! 👍

2022-12-19 17:57 UTC, PSchmiedmayer commented on Tests/HealthKitOnFHIRTests/HKCategorySampleTests.swift
> +            type: HKCategoryType(.audioExposureEvent),
I have reproduced this: The non-deprecated `HKCategoryType(.environmentalAudioExposureEvent)`'s string value is still `HKCategoryTypeIdentifierAudioExposureEvent`. Therefore you can still use that string key in the JSON and use the non-deprecated enum value in the JSON configuration. I have pushed this to the other branch and will create a PR for this to this branch 👍

2022-12-19 17:59 UTC, vishnuravi commented on Tests/HealthKitOnFHIRTests/HKCategorySampleTests.swift
> +            type: HKCategoryType(.audioExposureEvent),
Thanks. That is a bit confusing - perhaps we should report this as an issue to the HealthKit team.

2022-12-20 01:59 UTC, vishnuravi commented on Documentation/CATEGORY_TABLE.md
> +HealthKitOnFHIR supports 26 category types.
Have added this as well - thanks!

2022-12-20 02:00 UTC, vishnuravi commented on Tests/HealthKitOnFHIRTests/HKCategorySampleTests.swift
> +            type: HKCategoryType(.audioExposureEvent),
Have merged this in, thanks!

2022-12-20 02:22 UTC, PSchmiedmayer commented on Sources/HealthKitOnFHIR/HealthKit Extensions/HKCategoryValue+String.swift
> +            return "unknown"
I am not a huge fan of “magic” Strings that convey specific meaning and had see them fail quite often. Nevertheless, I see that is quite useful to have a conformance to `CustomStringConvertible`.

An idea on how we can achieve this and still throw errors if we can not support the conversion: You could still enable a conformance to `CustomStringConvertible` that might be useful for external dependencies if you use the new generated property, check for an error and then return a “magic” string but use the actual `categoryValueDescription` when dealing with the mapping within the framework or when you want to have the throwing error-based approach. 

You can just define one extension for all types as a default implementation that all types use and that you could even override on a per-type basis:

```swift
protocol HKCategoryValueDescription: CustomStringConvertible {
    var categoryValueDescription: String { get throws }
}


extension HKCategoryValueDescription {
    var description: String {
        do {
            return try categoryValueDescription
        } catch {
            return "undefined"
        }
    }
}
```

2022-12-20 05:06 UTC, vishnuravi commented on Sources/HealthKitOnFHIR/HealthKit Extensions/HKCategoryValue+String.swift
> +            return "unknown"
This is a great solution! I have implemented it in c622be3.

2022-12-20 05:23 UTC, PSchmiedmayer approved these changes
Looks great @vishnuravi 🚀

2022-12-20 08:21 UTC, merged