Add support for HKClinicalRecords
StanfordBDHG/HealthKitOnFHIR pull request #28
Opened 2022-12-29 19:40 UTC by vishnuravi

# Add support for HKClinicalRecords

## :bulb: Proposed solution
Converts HKClinicalRecords to FHIR resources based on FHIRModels.

### Testing
This library is designed to work with FHIR R4, however, the HKClinicalRecord samples within the iOS simulator are FHIR DSTU2, so they cannot be used for testing this code. We also cannot create our own HKClinicalRecords for tests.

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md):
- [X] I agree to follow the [Code of Conduct](https://github.com/StanfordBDHG/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordBDHG/.github/blob/main/CONTRIBUTING.md).

2023-01-05 20:02 UTC, PSchmiedmayer requested changes
@vishnuravi Thanks a lot for the improvement and addition support for `HKClinicalRecords` to the HealthKitOnFHIR package, very nice! 🚀

I have added multiple changes throughout the PR with a few smaller changes and a general bigger suggestion on keeping the overall API surface as simple and convenient as possible for developers using the Swift Package: I would suggest that the return type on the `HKSample` extensions should be a FHIR Module `ResourceProxy` that could be directly encoded or further inspected by a developer. As noted in my comments in the review that would make life a bit easier for developers and we could build most of the smarts in, e.g., mapping `HKClinicalRecords` directly in the HealthKitOnFHIR package.

Happy to hear your thoughts and comments! 🚀

2023-01-09 04:35 UTC, vishnuravi commented on Sources/HealthKitOnFHIR/HealthKitOnFHIRError.swift
> +    case invalidFHIRResource
Unfortunately the Apple documentation does not clarify this. I have added more context to the documentation.

2023-01-09 04:36 UTC, vishnuravi commented on Sources/HealthKitOnFHIR/HealthKit Extensions/HKClinicalRecord+Resource.swift
> +    func convert<T: Resource>(
This is a great suggestion @PSchmiedmayer! Will implement it.

2023-01-14 19:26 UTC, PSchmiedmayer approved these changes

2023-01-14 19:57 UTC, merged